pullRequests.grouping = [
  { name = "patches and minors", "title" = "Patch / minor backend updates", "filter" = [{"version" = "patch"}, {"version" = "minor"}] },
  { name = "Major upgrade", "title" = "Major upgrade for ${hash}", "filter" = [{"group" = "*"}] }
]