# Use postgres/example user/password credentials
version: "3.1"

services:
  izanami:
    #image: maif/izanami:2.16.1
    image: maif/izanami:2.23.2
    environment:
      IZANAMI_PG_HOST: host.docker.internal
      IZANAMI_CONTAINERIZED: true
      IZANAMI_PG_DATABASE: postgres
      IZANAMI_PG_USER: postgres
      IZANAMI_PG_PASSWORD: postgres
      IZANAMI_ADMIN_DEFAULT_USERNAME: izanami
      IZANAMI_ADMIN_DEFAULT_PASSWORD: password
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #    volumes:
    #      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 60s
      retries: 20
      start_period: 80s
